### ISSUE TITLE
希望docker增加arm64架构适配 I wish to adapt to the ARM64 architecture.

### ISSUE THREAD

**Issue by YongQI233** [MCSManager/Script#21]
**希望Docker安装方法添加ARM64的tag，适配ARM64架构
I wish to adapt to the ARM64 architecture.**

![image](https://github.com/MCSManager/Script/assets/85042877/b4784ae2-1bba-44e0-870a-21637de0771e)

**Comment by huangsijun17** [comment]
此Docker镜像并非由MCSM团队维护，建议前往[对应docker-compose仓库](https://github.com/zijiren233/docker-mcsm)询问。

**Comment by unitwk** [comment]
这个不是我们推出的镜像。
