### ISSUE TITLE
Docker images not available

### ISSUE THREAD

**Issue by ctron** [MCSManager/Script#22]
The docker images mentioned in https://github.com/MCSManager/Script/blob/master/docker/README.md seem to be no longer available:

```
docker pull bluefunny/mcsm-web:latest
Error response from daemon: pull access denied for bluefunny/mcsm-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by unitwk** [comment]
@FunnyShadow

**Comment by FunnyShadow** [comment]
Maybe I cleaned it up when I cleaned up the image earlier, I'll redo the workflow() that automatically builds the Docker image in a moment

**Comment by FunnyShadow** [comment]
Fixed
https://github.com/MCSManager/Script/pull/23

**Comment by FunnyShadow** [comment]
@unitwk close this issue pls
