### ISSUE TITLE
Update Node version?

### ISSUE THREAD

**Issue by D3SOX** [MCSManager/Script#24]
I think the install node step should be replaced by always the latest LTS version and if that isn't something that's guaranteed to be supported by MCSManager it should somewhere be defined as working version.

To not require it being updated all the time, you could also leverage something like [`fnm`](https://github.com/Schniz/fnm)

**Comment by unitwk** [comment]
The reason why we still do not use the latest lts is: in China, the default system of many service providers is the old version of Ubuntu, and we hope to continue to maintain compatibility.

**Comment by D3SOX** [comment]
I understand, so feel free to close this if you don't think you will change this in any way soon
