### ISSUE TITLE
Replace use of `sudo` and add root privileges check

### ISSUE THREAD

**Issue by D3SOX** [MCSManager/Script#25]
The script should probably check for root privileges and remove the obsolete use of `sudo` everywhere.
It really makes no sense, especially `sudo echo` is something that you'd think it works, but it doesn't. You'd have to pipe it into `sudo tee` for that.

**Comment by unitwk** [comment]
We will try to improve it, thank you for your feedback.

**Comment by unitwk** [comment]
Fixed
