### ISSUE TITLE
Error when running setup_en.sh : Unable to connect to github.com repository

### ISSUE THREAD

**Issue by Anonymous-AAAA** [MCSManager/Script#4]
When installing https://github.com/MCSManager
```bash
wget -qO- https://raw.githubusercontent.com/mcsmanager/Script/master/setup_en.sh | bash
```
ERROR : 
```bash
[+] Check network connection(ping github.com)... Fail
=================================================
[x] Unable to connect to github.com repository!
=================================================
```
This error is caused by line 237 in setup_en.sh : `if ping -c 1 github.com > /dev/null;`
github.com dosn't support ping anymore.

**Comment by huangsijun17** [comment]
Which Linux? Version?

**Comment by unitwk** [comment]
Fixed. Thanks for your feedback.

https://github.com/MCSManager/Script/commit/0925f9ae1b1b04c63ab56657f4254304d14e81cf

**Comment by Anonymous-AAAA** [comment]
> Which Linux? Version?

It didn't matter.
`ping` command do the same thing in every distribution/version

**Comment by huangsijun17** [comment]
I did use distros that didn't have `ping` installed.
Some small Linux installations will not come with network tools, such as `ping`, `ip`, `traceroute`.

**Comment by Anonymous-AAAA** [comment]
> I did use distros that didn't have `ping` installed. Some small Linux installations will not come with network tools, such as `ping`, `ip`, `traceroute`.

U're right, not all distros comes with `ping` command.

But in order to install this program, you should install network tools (Probably not necessary now), and this will still cause that prooblem due to github no longer support ping. So in my opinion, It didn't matter which distro or which version u use.
